# Generated by Django 5.0.2 on 2024-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_image_id_alter_image_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_image',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
