# Generated by Django 5.0.2 on 2024-08-04 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_image_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caracteristique',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
